# Generated by Django 4.2.4 on 2023-09-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gratitude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('one', models.CharField(max_length=150)),
                ('two', models.CharField(max_length=150)),
                ('three', models.CharField(max_length=150)),
                ('four', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
