# Generated by Django 4.2.4 on 2023-08-31 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gratitude', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gratitude',
            name='title',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
