# Generated by Django 4.2.4 on 2023-09-11 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gratitude', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gratitude',
            name='image',
            field=models.ImageField(upload_to='static/images/'),
        ),
    ]
