# Generated by Django 4.2.4 on 2023-08-31 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gratitude', '0002_gratitude_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gratitude',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
