# Generated by Django 4.2.4 on 2023-08-31 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gratitude', '0003_alter_gratitude_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gratitude',
            name='image',
        ),
    ]
