# Generated by Django 4.2.4 on 2023-09-03 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gratitude', '0005_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='gratitude',
            name='image',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='gratitude.photo'),
            preserve_default=False,
        ),
    ]
