# Generated by Django 4.2.4 on 2023-09-05 12:57

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gratitude', '0006_gratitude_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gratitude',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
