# Generated by Django 4.2.4 on 2023-09-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MathProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num1', models.IntegerField()),
                ('num2', models.IntegerField()),
                ('answer', models.IntegerField()),
                ('user_response', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
