# Generated by Django 4.2.4 on 2023-09-13 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comments',
            field=models.TextField(max_length=200),
        ),
    ]
