# Generated by Django 4.2.4 on 2023-09-14 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_rename_comments_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
